site_name: Cuadratura Gaussiana

theme:
  name: material

# Navegación requerida por la rúbrica
nav:
  - Introducción: index.md
  - Explicación: explanation.md
  - Tutoriales: tutorials.md
  - Referencia del Código: reference.md

# Plugins para generar la documentación de tu código
plugins:
  - mkdocstrings

# Extensiones para soportar LaTeX (Apéndice de la tarea)
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
